import os.path

Import('context')

context.module(
        name = "utilUnitTest",
        srcs = context.SRCS_ALL,
        targetType = context.TYPE_EXE,
        libs = context.split("""
                #any external libs  that you may need.
        """),
        wholeLibs = context.split("""
               gmock
        """),
        requiredLibs = context.split("""
                cool
                #boost_python
                #boost_thread
        """)
)

