INFO_FILE_OPERATION_SUCCESS = 100
INFO_FILE_ACCEPTED = 200

INFO_FILE_MOUNT_CHECK_FAILED = 10
INFO_FILE_NOT_FOUND=20
INFO_FILE_ALREADY_EXIST=30
INFO_FILE_OPERATION_ERROR=40
INFO_FILE_INTERNAL_ERROR=50
INFO_FILE_DELETED = 55

INFO_FILE_MAX_META_COUNT_REACHED = 70
INFO_FILE_MAX_META_SIZE_REACHED = 71
INFO_FILE_MAX_ACL_SIZE_REACHED = 73
INFO_FILE_MAX_SYSTEM_META_SIZE_REACHED = 75

CMD_ERR_BAD_CONFIG_ERROR=60
