import os.path

Import('context')

context.module(
	name = "accountLib",
	#srcs = context.SRCS_ALL,
	srcs = context.split("""
		record_structure.cpp
		trailer_stat_block_builder.cpp
		trailer_stat_block_writer.cpp
		account_record_iterator.cpp
		reader.cpp
		writer.cpp
		account_info_file_manager.cpp
		account_info_file_builder.cpp
		account_info_file.cpp
		non_static_data_block.cpp
		non_static_data_block_builder.cpp
		non_static_data_block_writer.cpp
		static_data_block.cpp
		static_data_block_builder.cpp
		static_data_block_writer.cpp
		account_library.cpp
		python_binding.cpp
		../libraryUtils/info_file_sorter.cpp
		../libraryUtils/object_storage_log_setup.cpp
		../libraryUtils/file_handler.cpp
		../libraryUtils/lock_manager.cpp
		../libraryUtils/osd_logger_initialize.cpp
	"""),
	
        targetType = context.TYPE_DLL,
        libs = context.split("""
                #any external libs  that you may need.
		#libraryUtils
        """),
        # only in case of unit test dir
        #wholeLibs = context.split("""
        #       gmock
        #""")
        requiredLibs = context.split("""
                boost_python
                boost_thread
		boost_thread-mt
		boost_system
		cool
		boost_filesystem
		#libraryUtils
        """)
)

